version: '3.7'

services:
  db:
    container_name: events_db
    image: postgres:16.3
    volumes:
      - ./data/db:/var/lib/postgresql/data
    env_file:
      - ./app/.env
    environment:
      - TZ=GMT+2
      - PGTZ=GMT+2
    networks:
      - events_network

  events:
    container_name: events
    build:
      context: .
      dockerfile: ./dockerfiles/Dockerfile_app_deploy
    volumes:
      - static_data:/vol/web
    depends_on:
      - db
    networks:
      - events_network

  rabbitmq:
    container_name: events_rabbit
    hostname: rabbit_host
    build:
      context: ./rabbitmq
      # TBD Be careful with path here. Context is /rabbitmq so the paths of the Dockerfile
      # are within /rabbitmq (different to the other Dockerfiles)
      dockerfile: Dockerfile_deploy
    env_file:
      - ./app/.env
    # TBD Was machen wir damit??
    ports:
      - 5672:5672    #amqp
      - 15672:15672  #http
      - 15692:15692  #prometheus
    networks:
      - events_network

  celery_worker:
    container_name: events_celery_worker
    build:
      context: .
      dockerfile: ./dockerfiles/Dockerfile_celery_worker
    volumes:
      - ./app:/app
    depends_on:
      - events
      - rabbitmq
      - db
    networks:
      - events_network

  celery_beat:
    container_name: events_celery_beat
    build:
      context: .
      dockerfile: ./dockerfiles/Dockerfile_celery_beat
    volumes:
      - ./app:/app
    depends_on:
      - events
      - rabbitmq
      - db
    networks:
      - events_network

  nginx:
    container_name: events_nginx
    build:
      context: ./nginx
    volumes:
      - static_data:/vol/static
    ports:
      - "44445:8080"
    depends_on:
      - events
    networks:
      - events_network

volumes:
  static_data:

networks:
  events_network:
    name: events_network
    driver: bridge
