# Generated by Django 4.2 on 2024-04-18 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='utmember',
            constraint=models.UniqueConstraint(fields=('member_number',), name='member_number is unique'),
        ),
    ]
