# Generated by Django 4.2 on 2024-07-27 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['date'], 'verbose_name': 'Veranstaltung', 'verbose_name_plural': 'Veranstaltungen'},
        ),
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=models.CharField(choices=[('AD', 'Einlass'), ('BR', 'Bar'), ('RG', 'Reinigung'), ('KÜ', 'Küche'), ('LT', 'Lichttechnik'), ('TT', 'Tontechnik'), ('OT', 'Sonstiges')], default='OT', max_length=2, verbose_name='Aufgabenart'),
        ),
        migrations.AlterOrderWithRespectTo(
            name='task',
            order_with_respect_to='event',
        ),
        migrations.AlterOrderWithRespectTo(
            name='volunteering',
            order_with_respect_to='task',
        ),
    ]
