# Generated by Django 4.2 on 2024-02-06 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='teammember',
            constraint=models.UniqueConstraint(fields=('username', 'team_name'), name='prevent multiple memberships of one person in one team constraint'),
        ),
    ]
