# Generated by Django 4.2 on 2024-01-27 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('setting_name', models.CharField(primary_key=True, serialize=False)),
                ('setting_type', models.CharField(choices=[('NG', 'Benachrichtigungen allgmein'), ('NS', 'Bestimmte Benachrichtigung'), ('AP', 'Erscheinungsbild'), ('ST', 'Einstellung')], default='ST', max_length=2)),
                ('value_type', models.CharField(choices=[('BO', 'Bool'), ('IN', 'Integer'), ('EN', 'Eumeration')], default='BO', max_length=2)),
            ],
            options={
                'verbose_name': 'Einstellung',
                'verbose_name_plural': 'Einstellungen',
            },
        ),
        migrations.CreateModel(
            name='UserSettingValue',
            fields=[
                ('user_setting_value_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('setting_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.setting')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.user')),
            ],
            options={
                'verbose_name': 'Einstellungswert',
                'verbose_name_plural': 'Einstellungswerte',
            },
        ),
        migrations.AlterModelOptions(
            name='tasknotification',
            options={'verbose_name': 'Aufgabenbenachrichtigung'},
        ),
        migrations.AlterModelOptions(
            name='volunteer',
            options={'verbose_name': 'Helfer:in'},
        ),
        migrations.AlterModelOptions(
            name='volunteeringnotification',
            options={'verbose_name': 'Dienstbenachrichtigung'},
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('CI', 'Kino'), ('CO', 'Konzert'), ('PY', 'Theater'), ('FV', 'Festival'), ('OT', 'Sonstiges')], default='OT', max_length=2),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('AB', 'Aufgabenbenachrichtigung'), ('DB', 'Dienstbenachrichtigung'), ('BN', 'Benachrichtigung')], default='BN', max_length=2),
        ),
        migrations.AlterField(
            model_name='task',
            name='state',
            field=models.CharField(choices=[('FR', 'Offen'), ('TK', 'Übernommen'), ('MB', 'Vielleicht'), ('DN', 'Erledigt')], default='FR', max_length=2),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=models.CharField(choices=[('AD', 'Einlass'), ('TT', 'Tontechnik'), ('LT', 'Lichttechnik'), ('KÜ', 'Küche'), ('OT', 'Sonstiges')], default='OT', max_length=2),
        ),
        migrations.AlterField(
            model_name='task',
            name='team_restriction',
            field=models.CharField(choices=[('TT', 'Tontechnik'), ('LT', 'Lichttechnik'), ('VW', 'Verwaltung'), ('NO', 'Ohne')], default='NO', max_length=2),
        ),
        migrations.AlterField(
            model_name='task',
            name='urgency',
            field=models.CharField(choices=[('UR', 'Dringend'), ('IM', 'Wichtig'), ('MD', 'Mittel'), ('LO', 'Niedrig')], default='MD', max_length=2),
        ),
        migrations.AlterField(
            model_name='volunteering',
            name='confirmation_type',
            field=models.CharField(choices=[('NO', 'Nicht'), ('CE', 'Sicher'), ('MB', 'Vielleicht')], default='NO', max_length=15),
        ),
        migrations.CreateModel(
            name='BoolValue',
            fields=[
                ('usersettingvalue_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='backend.usersettingvalue')),
                ('bool_value', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Boolwert',
            },
            bases=('backend.usersettingvalue',),
        ),
        migrations.CreateModel(
            name='EnumValue',
            fields=[
                ('usersettingvalue_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='backend.usersettingvalue')),
            ],
            options={
                'verbose_name': 'Enumwert',
            },
            bases=('backend.usersettingvalue',),
        ),
        migrations.CreateModel(
            name='IntValue',
            fields=[
                ('usersettingvalue_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='backend.usersettingvalue')),
                ('int_value', models.BigIntegerField()),
            ],
            options={
                'verbose_name': 'Integerwert',
            },
            bases=('backend.usersettingvalue',),
        ),
    ]
