# Generated by Django 4.2 on 2024-07-27 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_event_options_alter_task_task_type_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='team',
            constraint=models.UniqueConstraint(fields=('name',), name='prevent teamname duplicates constraint'),
        ),
    ]
