# Generated by Django 4.2 on 2024-02-05 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_setting_usersettingvalue_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='act',
            options={'verbose_name': 'Akt', 'verbose_name_plural': 'Akte'},
        ),
        migrations.AlterModelOptions(
            name='adress',
            options={'verbose_name': 'Adresse', 'verbose_name_plural': 'Adressen'},
        ),
        migrations.AlterModelOptions(
            name='boolvalue',
            options={'verbose_name': 'Boolwert', 'verbose_name_plural': 'Boolwerte'},
        ),
        migrations.AlterModelOptions(
            name='enumvalue',
            options={'verbose_name': 'Enumwert', 'verbose_name_plural': 'Enumwerte'},
        ),
        migrations.AlterModelOptions(
            name='intvalue',
            options={'verbose_name': 'Integerwert', 'verbose_name_plural': 'Integerwerte'},
        ),
        migrations.AlterModelOptions(
            name='tasknotification',
            options={'verbose_name': 'Aufgabenbenachrichtigung', 'verbose_name_plural': 'Aufgabenbenachrichtigungen'},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'verbose_name': 'Team', 'verbose_name_plural': 'Teams'},
        ),
        migrations.AlterModelOptions(
            name='teammember',
            options={'verbose_name': 'Teammitglied', 'verbose_name_plural': 'Teammitglieder'},
        ),
        migrations.AlterModelOptions(
            name='utmember',
            options={'verbose_name': 'Mitglied', 'verbose_name_plural': 'Mitglieder'},
        ),
        migrations.AlterModelOptions(
            name='volunteer',
            options={'verbose_name': 'Helfer:in', 'verbose_name_plural': 'Helfer:innen'},
        ),
        migrations.AlterModelOptions(
            name='volunteeringnotification',
            options={'verbose_name': 'Dienstbenachrichtigung', 'verbose_name_plural': 'Dienstbenachrichtigungen'},
        ),
        migrations.RemoveField(
            model_name='user',
            name='password',
        ),
        migrations.AlterField(
            model_name='act',
            name='act_email',
            field=models.EmailField(blank=True, max_length=100, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='act',
            name='act_image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Bild'),
        ),
        migrations.AlterField(
            model_name='act',
            name='act_name',
            field=models.CharField(max_length=40, primary_key=True, serialize=False, verbose_name='Aktname'),
        ),
        migrations.AlterField(
            model_name='act',
            name='act_phone',
            field=models.CharField(blank=True, max_length=15, verbose_name='Telefon'),
        ),
        migrations.AlterField(
            model_name='act',
            name='diet',
            field=models.CharField(blank=True, max_length=100, verbose_name='Ernährung'),
        ),
        migrations.AlterField(
            model_name='act',
            name='music_sample',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Musikbeispiel'),
        ),
        migrations.AlterField(
            model_name='act',
            name='person_count',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Personenzahl'),
        ),
        migrations.AlterField(
            model_name='adress',
            name='country',
            field=models.CharField(blank=True, max_length=40, verbose_name='Land'),
        ),
        migrations.AlterField(
            model_name='adress',
            name='house_number',
            field=models.CharField(blank=True, max_length=40, verbose_name='Hausnummer'),
        ),
        migrations.AlterField(
            model_name='adress',
            name='postal_code',
            field=models.CharField(blank=True, max_length=40, verbose_name='PLZ'),
        ),
        migrations.AlterField(
            model_name='adress',
            name='street',
            field=models.CharField(blank=True, max_length=40, verbose_name='Straße'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_description',
            field=models.TextField(blank=True, verbose_name='Beschreibung'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Einlassgebühr'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Bild'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_name',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Veranstaltungsname'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_press',
            field=models.TextField(blank=True, verbose_name='Pressetext'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('CI', 'Kino'), ('CO', 'Konzert'), ('PY', 'Theater'), ('FV', 'Festival'), ('OT', 'Sonstiges')], default='OT', max_length=2, verbose_name='Veranstaltungsart'),
        ),
        migrations.AlterField(
            model_name='eventday',
            name='admission_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Einlassbeginn'),
        ),
        migrations.AlterField(
            model_name='eventday',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Datum'),
        ),
        migrations.AlterField(
            model_name='eventday',
            name='duration',
            field=models.DurationField(blank=True, null=True, verbose_name='Veranstaltungsdauer'),
        ),
        migrations.AlterField(
            model_name='eventday',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Veranstaltungsbeginn'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Kommentar'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('AB', 'Aufgabenbenachrichtigung'), ('DB', 'Dienstbenachrichtigung'), ('BN', 'Benachrichtigung')], default='BN', max_length=2, verbose_name='Benachrichtigungsart'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='timer',
            field=models.PositiveIntegerField(verbose_name='Timer'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='setting_name',
            field=models.CharField(primary_key=True, serialize=False, verbose_name='Einstellungsname'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='setting_type',
            field=models.CharField(choices=[('NG', 'Benachrichtigungen allgmein'), ('NS', 'Bestimmte Benachrichtigung'), ('AP', 'Erscheinungsbild'), ('ST', 'Einstellung')], default='ST', max_length=2, verbose_name='Einstellungsart'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='value_type',
            field=models.CharField(choices=[('BO', 'Bool'), ('IN', 'Integer'), ('EN', 'Eumeration')], default='BO', max_length=2, verbose_name='Datentyp'),
        ),
        migrations.AlterField(
            model_name='task',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Kommentar'),
        ),
        migrations.AlterField(
            model_name='task',
            name='finish_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ende'),
        ),
        migrations.AlterField(
            model_name='task',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Beginn'),
        ),
        migrations.AlterField(
            model_name='task',
            name='state',
            field=models.CharField(choices=[('FR', 'Offen'), ('TK', 'Übernommen'), ('MB', 'Vielleicht'), ('DN', 'Erledigt')], default='FR', max_length=2, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=models.CharField(choices=[('AD', 'Einlass'), ('TT', 'Tontechnik'), ('LT', 'Lichttechnik'), ('KÜ', 'Küche'), ('OT', 'Sonstiges')], default='OT', max_length=2, verbose_name='Aufgabenart'),
        ),
        migrations.AlterField(
            model_name='task',
            name='team_restriction',
            field=models.CharField(choices=[('TT', 'Tontechnik'), ('LT', 'Lichttechnik'), ('VW', 'Verwaltung'), ('NO', 'Ohne')], default='NO', max_length=2, verbose_name='Teambindung'),
        ),
        migrations.AlterField(
            model_name='task',
            name='urgency',
            field=models.CharField(choices=[('UR', 'Dringend'), ('IM', 'Wichtig'), ('MD', 'Mittel'), ('LO', 'Niedrig')], default='MD', max_length=2, verbose_name='Dringlichkeit'),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_name',
            field=models.CharField(max_length=40, primary_key=True, serialize=False, verbose_name='Teamname'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=40, verbose_name='Nachname'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Telefon'),
        ),
        migrations.AlterField(
            model_name='user',
            name='surname',
            field=models.CharField(blank=True, max_length=40, verbose_name='Vorname'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Anmeldename'),
        ),
        migrations.AlterField(
            model_name='utmember',
            name='member_number',
            field=models.PositiveIntegerField(verbose_name='Mitgliedsnummer'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='volunteering_count',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Zähler'),
        ),
        migrations.AlterField(
            model_name='volunteering',
            name='confirmation_type',
            field=models.CharField(choices=[('NO', 'Nicht'), ('CE', 'Sicher'), ('MB', 'Vielleicht')], default='NO', max_length=15, verbose_name='Art der Zusage'),
        ),
    ]
