# Generated by Django 4.2 on 2024-02-06 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_alter_act_options_alter_adress_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adress',
            name='id',
        ),
        migrations.AlterField(
            model_name='adress',
            name='username',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='backend.user'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('CI', 'Kino'), ('CO', 'Musik'), ('PL', 'Bühne'), ('PY', 'Party'), ('EX', 'Extra'), ('FV', 'Festival'), ('OT', 'Sonstiges')], default='OT', max_length=2, verbose_name='Veranstaltungsart'),
        ),
    ]
