# Generated by Django 4.2 on 2024-05-02 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_delete_volunteer'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='volunteering',
            constraint=models.UniqueConstraint(fields=('task',), name='prevent multiple volunteerings for one task constraint'),
        ),
    ]
