# Generated by Django 4.2 on 2024-06-21 12:23

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('backend', '0003_alter_teammember_options_alter_utmember_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Team',
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
            ],
            options={
                'verbose_name': 'Team',
                'verbose_name_plural': 'Teams',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.group',),
            managers=[
                ('objects', django.contrib.auth.models.GroupManager()),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='Teams zu welchen die Person gehört. Alle Befugnisse einer Gruppe gehen auf die Person über', related_name='user_set', related_query_name='user', through='backend.TeamMember', to='backend.team'),
        ),
    ]
