# Generated by Django 4.2 on 2024-07-27 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_pastevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pastevent',
            name='date',
            field=models.DateField(verbose_name='Datum'),
        ),
        migrations.AlterField(
            model_name='pastevent',
            name='start_time',
            field=models.TimeField(verbose_name='Veranstaltungsbeginn'),
        ),
    ]
