# Generated by Django 4.2 on 2024-05-02 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_volunteering_prevent_multiple_volunteerings_for_one_task_constraint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=models.CharField(choices=[('AD', 'Einlass'), ('TT', 'Tontechnik'), ('LT', 'Lichttechnik'), ('KÜ', 'Küche'), ('BR', 'Bar'), ('OT', 'Sonstiges')], default='OT', max_length=2, verbose_name='Aufgabenart'),
        ),
    ]
