# Generated by Django 4.2 on 2024-06-26 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_delete_team_team_alter_user_groups'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
