# Generated by Django 4.2 on 2024-05-03 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_alter_task_task_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteering',
            name='comment',
            field=models.TextField(blank=True, max_length=300, verbose_name='Kommentar'),
        ),
        migrations.AlterField(
            model_name='volunteering',
            name='confirmation_type',
            field=models.CharField(choices=[('NO', 'Nein'), ('YS', 'Ja')], default='YS', max_length=15, verbose_name='Zusage'),
        ),
    ]
