# Generated by Django 4.2 on 2024-05-24 12:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_volunteering_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventday',
            name='date',
            field=models.DateField(verbose_name='Datum'),
        ),
        migrations.AlterField(
            model_name='eventday',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.event', verbose_name='Veranstaltung'),
        ),
        migrations.AlterField(
            model_name='task',
            name='event_day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.eventday', verbose_name='Veranstaltungstag'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_id',
            field=models.BigAutoField(primary_key=True, serialize=False, verbose_name='Veranstaltungstag'),
        ),
        migrations.AlterField(
            model_name='volunteering',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.task', verbose_name='Aufgabe'),
        ),
        migrations.AlterField(
            model_name='volunteering',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Person'),
        ),
    ]
