# Generated by Django 4.2 on 2024-05-28 13:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_alter_eventday_date_alter_eventday_event_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeletedVolunteering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(verbose_name='Zeitpunkt')),
                ('comment', models.TextField(blank=True, max_length=300, verbose_name='Kommentar')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.task', verbose_name='Aufgabe')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Person')),
            ],
            options={
                'verbose_name': 'Gelöschter Dienst',
                'verbose_name_plural': 'Gelöschte Dienste',
            },
        ),
        migrations.AddConstraint(
            model_name='deletedvolunteering',
            constraint=models.UniqueConstraint(fields=('task',), name='prevent multiple deletd volunteerings for one task constraint'),
        ),
    ]
