# Generated by Django 4.2 on 2024-05-28 13:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_deletedvolunteering_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deletedvolunteering',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Person'),
        ),
    ]
