# Generated by Django 4.2 on 2024-05-28 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_alter_deletedvolunteering_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deletedvolunteering',
            name='task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.task', verbose_name='Aufgabe'),
        ),
    ]
