# Generated by Django 4.2 on 2024-05-29 09:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_alter_deletedvolunteering_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deletedvolunteering',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Person'),
        ),
        migrations.AlterField(
            model_name='task',
            name='state',
            field=models.CharField(choices=[('FR', 'Offen'), ('TK', 'Übernommen'), ('MB', 'Vielleicht'), ('DN', 'Erledigt')], default='FR', editable=False, max_length=2, verbose_name='Status'),
        ),
    ]
