# Generated by Django 4.2 on 2024-05-29 10:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_alter_eventday_admission_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventday',
            name='start_time',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='Veranstaltungsbeginn'),
        ),
    ]
