# Generated by Django 4.2 on 2024-06-15 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_alter_eventday_start_time'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='eventday',
            constraint=models.UniqueConstraint(fields=('date', 'start_time'), name='prevent event_day duplicates constraint'),
        ),
    ]
