FROM rabbitmq:3.13-management-alpine

RUN mkdir -p /etc/rabbitmq/conf.d
RUN chown -R rabbitmq:rabbitmq /etc/rabbitmq/conf.d
COPY 20-logging.conf /etc/rabbitmq/conf.d

ENV RABBITMQ_PID_FILE /var/lib/rabbitmq/mnesia/rabbitmq

ADD init-deploy.sh /init-deploy.sh
RUN chmod +x /init-deploy.sh
EXPOSE 4369 5671 5672 15671 15672 25672 35672-35682

# set up user and run rabbit server
CMD ["/init-deploy.sh"]
